---

- name: APT | Install dependencies
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    dpkg_options: 'force-confnew,force-confdef'
    autoclean: true
    autoremove: true
    update_cache: true
    cache_valid_time: 3600
  vars:
    packages:
    - software-properties-common
    - gnupg2

- name: APT | Add golang-backports
  ansible.builtin.apt_repository:
    repo: 'ppa:longsleep/golang-backports'

- name: APT | Install golang
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    dpkg_options: 'force-confnew,force-confdef'
    autoclean: true
    autoremove: true
    update_cache: true
    cache_valid_time: 3600
  vars:
    packages:
    - golang-{{ golang_version }}

- name: Iterate golang_users
  ansible.builtin.include_tasks: user.yml
  with_items: "{{ golang_users }}"
  loop_control:
    loop_var: golang_user

...
