---

- name: GoLang | Create gopath directories
  ansible.builtin.file:
    path: "{{ (golang_user == 'root') | ternary('/root/' + golang_gopath, '/home/' + golang_user + '/' + golang_gopath) }}"
    state: directory
    owner: "{{ golang_user }}"
    group: "{{ golang_user }}"
    mode: "0755"

- name: GoLang | Add go binaries and GOPATH to .profile
  ansible.builtin.blockinfile:
    path: "{{ (golang_user == 'root') | ternary('/root/.profile', '/home/' + golang_user + '/.profile') }}"
    block: |
      export GOPATH=$HOME/{{ golang_gopath }}
      export PATH="$PATH:${GOPATH}/bin:/snap/bin"
    marker: "# {mark} go binaries and go path"

- name: GoLang | Create gopath sub-directories
  ansible.builtin.file:
    path: "{{ (golang_user == 'root') | ternary('/root/' + golang_gopath + '/' + item, '/home/' + golang_user + '/' + golang_gopath + '/' + item) }}"
    state: directory
    owner: "{{ golang_user }}"
    group: "{{ golang_user }}"
    mode: "0755"
  with_items:
  - bin
  - src
  - pkg

- name: GoLang | Install go libraries
  ansible.builtin.shell: "source $HOME/.profile; go install {{ item }}"
  args:
    executable: /bin/bash
  become: true
  become_user: "{{ golang_user }}"
  with_items: "{{ golang_additional_libraries }}"
  changed_when: false

...
