---
- hosts: all
  become: true
  become_method: sudo

  vars:

    golang_version: '1.21'
    golang_gopath: go
    golang_additional_libraries:
    - golang.org/x/tools/cmd/goimports@latest
    golang_users:
    - root
    - vagrant

  pre_tasks:
  - name: check for file custom_vars.yml
    stat:
      path: custom_vars.yml
    register: stat_custom_vars
  - name: load custom vars, if existent
    include_vars:
      file: custom_vars.yml
    when: stat_custom_vars.stat.exists

  roles:
  - andrelohmann.root_colored_prompt
  - ansible-role-golang

...
