---
- name: Converge
  hosts: all
  become: true
  become_method: ansible.builtin.sudo

  vars:
    golang_version: 'latest'
    golang_gopath: go
    golang_additional_libraries:
    - golang.org/x/tools/cmd/goimports@latest
    golang_users:
    - root

  tasks:
  - name: Include andrelohmann.golang
    ansible.builtin.include_role:
      name: "andrelohmann.golang"
...
