---
- name: Converge
  hosts: all

  vars:
    golang_version: '1.21'
    golang_gopath: go
    golang_additional_libraries:
    - golang.org/x/tools/cmd/goimports@latest
    golang_users:
    - root

  tasks:
  - name: "Include andrelohmann.golang"
    include_role:
      name: "andrelohmann.golang"
...
