---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:

  - name: Run go version
    ansible.builtin.shell: source $HOME/.profile; go version
    args:
      executable: /bin/bash
    register: go_version
    changed_when: false

  - name: Dump go version
    ansible.builtin.debug:
      var: go_version

  - name: Assert the go is installed
    ansible.builtin.assert:
      that: go_version.stdout is search('go version go')

...
